import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Small Blog App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  const stylesNav = {
    background: 'teal',
    fontSize: '30px',
    height: '100px',
    margin: "0",
    display: 'flex'

  }
  const divStyle = {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: '50%',
    height: '100%'

  }
  const spItem = {
    marginRight: '15px'
  }
  const logoStyle = {
    color: "orange",
    fontSize: "45px",
    marginLeft: '10px',

  }
  const shereWid = {
    width: '50%',
    height: '100%',
    display: "flex",
    alignItems: "center",
  }
  const redGround = {
    color: 'red'
  };
  const greenGround = {
    color: 'green'
  };
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={stylesNav}>

          <div style={shereWid}>
            <Link href={'/'}>
              <p style={logoStyle}>B<span style={redGround}>l</span><span style={greenGround}>O</span>g</p>
            </Link>
          </div>

          <div style={divStyle}>
            <Link href={'/'}>
              <p style={spItem}>Front-End</p>
            </Link>

            <Link href={'/'}>
              <p style={spItem}>Food</p>
            </Link>

            <Link href={'/'}>
              <p style={spItem}>Sport</p>
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
